config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kitchen/urls.py
from django.urls import path

from kitchen.views import (
    index,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishDeleteView,
    DishUpdateView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookDeleteView,
    CookUpdateView,
    DishTypeDetailView,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeDeleteView,
    DishTypeUpdateView,
)

urlpatterns = [
    path("", index, name="index"),
    path("dishes/", DishListView.as_view(), name="dishes-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/delete", DishDeleteView.as_view(), name="dish-delete"),
    path("dishes/<int:pk>/update", DishUpdateView.as_view(), name="dish-update"),
    path("dishes-types/", DishTypeListView.as_view(), name="dish-type-list"),
    path("dishes-types/<int:pk>/", DishTypeDetailView.as_view(), name="dish-type-detail"),
    path(
        "dishes-types/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create"
    ),
    path(
        "dishes-types/<int:pk>/delete",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete"
    ),
    path(
        "dishes-types/<int:pk>/update",
        DishTypeUpdateView.as_view(),
        name="dish-type-update"
    ),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path(""
         "cooks/<int:pk>/delete",
         CookDeleteView.as_view(),
         name="cook-delete"
         ),
    path(
        "cooks/<int:pk>/update",
        CookUpdateView.as_view(),
        name="cook-update"
    ),
    path("signup/", CookCreateView.as_view(), name="user-create")
]

app_name = "kitchen"

kitchen/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(null=False, blank=True)

    def __str__(self) -> str:
        return self.username


class DishType(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self) -> str:
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=63)
    description = models.TextField(null=False)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE, related_name="dishes")
    cooks = models.ManyToManyField(get_user_model(), related_name="cooks")

    def __str__(self) -> str:
        return self.name

kitchen/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django import forms

from kitchen.models import Dish, DishType, Cook


class DishForm(ModelForm):
    class Meta:
        model = Dish
        fields = "__all__"

    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )


class DishTypeForm(ModelForm):
    class Meta:
        model = DishType
        fields = "__all__"


class CookForm(ModelForm):

    class Meta:
        model = get_user_model()
        fields = ("years_of_experience", "first_name", "last_name")


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ("years_of_experience", )

kitchen/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from kitchen.forms import DishForm, DishTypeForm, CookForm, CookCreationForm
from kitchen.models import Cook, Dish, DishType


def index(request: HttpRequest) -> HttpResponse:
    num_cooks = get_user_model().objects.count()
    num_dish = Dish.objects.count()
    num_dish_type = DishType.objects.count()
    context = {
        "num_cooks": num_cooks,
        "num_dish": num_dish,
        "num_dish_type": num_dish_type,
    }
    return render(request, "kitchen/index.html", context=context)


class DishListView(generic.ListView):
    model = Dish
    paginate_by = 5
    context_object_name = "dish_list"


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    success_url = reverse_lazy("kitchen:dishes-list")
    form_class = DishForm
    context_object_name = "dish_create"


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen:dishes-list")
    context_object_name = "dish-delete"


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    success_url = reverse_lazy("kitchen:dishes-list")
    form_class = DishForm
    context_object_name = "dish-update"


class DishTypeListView(generic.ListView):
    model = DishType
    context_object_name = "dish_type_list"
    paginate_by = 5


class DishTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = DishType


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    success_url = reverse_lazy("kitchen:dish-type-list")
    form_class = DishTypeForm
    context_object_name = "dish_type_create"


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    success_url = reverse_lazy("kitchen:dish-type-list")
    form_class = DishTypeForm
    context_object_name = "dish-type-delete"


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    success_url = reverse_lazy("kitchen:dish-type-list")
    form_class = DishTypeForm
    context_object_name = "dish-type-update"


class CookListView(generic.ListView):
    model = Cook
    context_object_name = "cook_list"
    paginate_by = 5


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("kitchen:cook-list")
    context_object_name = "cook-delete"
    form_class = CookForm


class CookCreateView(generic.CreateView):
    model = Cook
    success_url = reverse_lazy("kitchen:cook-list")
    context_object_name = "cook-create"
    form_class = CookCreationForm


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    success_url = reverse_lazy("kitchen:cook-list")
    form_class = CookForm
    context_object_name = "user-create"

templates/_base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Kitchen Service</title>{% endblock %}
  <meta charset="utf-8">
  {% load static %}
  <link rel="stylesheet" href="{% static "css/styles.css" %}">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body class="background">
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" href="{% url "kitchen:index" %}">Home
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "kitchen:dishes-list" %}">Our Dishes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "kitchen:dish-type-list" %}">Our Dishes Types</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "kitchen:cook-list" %}">Our Cooks</a>
        </li>
      </ul>
      <form class="d-flex">
        {% if user.is_authenticated %}
          <a class="btn btn-secondary my-2 my-sm-0" href="{% url "logout" %}">Logout</a>
        {% else %}
          <a class="btn my-2 my-sm-0" href="{% url "kitchen:user-create" %}">Sign Up</a>
          <a class="btn btn-secondary my-2 my-sm-0" href="{% url "login" %}">Login</a>
        {% endif %}
      </form>
    </div>
  </div>
</nav>
{% block content %}{% endblock %}
      {% block pagination %}
        {% include "includes/pagination.html" %}
      {% endblock %}
</body>
</html>

templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
  <div class="paginator">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link"><</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">></a>
      </li>
    {% endif %}
  </ul>
  </div>
{% endif %}

templates/kitchen/cook_confirm_delete.html
{% extends "_base.html" %}

{% block content %}
  <h1>Are you sure you want to delete?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/kitchen/cook_detail.html
{% extends "_base.html" %}

{% block content %}
  <ul>
    <li class="list-group-item d-flex justify-content-between align-items-center">{{ cook.first_name }}</li>
    <li class="list-group-item d-flex justify-content-between align-items-center">{{ cook.last_name }}</li>
    <li class="list-group-item d-flex justify-content-between align-items-center">{{ cook.years_of_experience }}</li>
  </ul>
{% endblock %}

templates/kitchen/cook_form.html
{% extends "_base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Cook Update,Cook Registration" }}</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/cook_list.html
{% extends "_base.html" %}

{% block content %}
  {% load static %}
  <link rel="stylesheet" href="{% static "css/settings.css" %}">
  <div class="element middle">
    <table class="table">
      <tr>
        <th>Cook Name</th>
        <th>Experience</th>
        {% if user.is_staff %}
          <th>Edit</th>
          </tr>
        {% endif %}
      {% for cook in cook_list %}
        <tr>
          {% if user.is_staff %}
            <td><a class="links" href="{% url "kitchen:cook-detail" pk=cook.id %}"> {% if cook.first_name %}
              {{ cook.first_name }} {% else %} {{ cook }} {% endif %}</a></td>
          {% else %}
            <td>{% if cook.first_name %} {{ cook.first_name }} {% else %} {{ cook }} {% endif %}</td>
          {% endif %}
          <td>{% if cook.years_of_experience %} {{ cook.years_of_experience }} year{{ cook.years_of_experience|pluralize }}
          {% else %} - {% endif %}</td>
          {% if user.is_staff %}
            <td><a class="links" href="{% url "kitchen:cook-update" pk=cook.id %}">Update </a><a class="links"
                                                                                                 href="{% url "kitchen:cook-delete" pk=cook.id %}">Delete</a>
            </td>
          {% endif %}
        </tr>
      {% endfor %}
    </table>
  </div>
{% endblock %}

templates/kitchen/dish_cofirm_delete.html
{% extends "_base.html" %}

{% block content %}
  <h1>Delete {{ dish.name }}?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/kitchen/dish_confirm_delete.html
{% extends "_base.html" %}

{% block content %}
  <h1>Are you sure you want to delete?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/kitchen/dish_detail.html
{% extends "_base.html" %}


{% block content %}
  <ul>
    <li>{{ dish.name }}</li>
    <li>{{ dish.description }}</li>
    <li>{{ dish.price }}</li>
    <li>{{ dish.dish_type }}</li>
    <li>{{ dish.cooks.name }}</li>
    <li><a href="{% url "kitchen:dish-update" pk=dish.id %}">Update {{ dish.name }}</a></li>
    <li><a href="{% url "kitchen:dish-delete" pk=dish.id %}">Delete {{ dish.name }}</a></li>
  </ul>
{% endblock %}

templates/kitchen/dish_form.html
{% extends "_base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/dish_list.html
{% extends "_base.html" %}

{% block content %}
  {% load static %}
  <link rel="stylesheet" href="{% static "css/settings.css" %}">
  <div class="element middle">
    <table class="table">
      <tr>
        <th>Dish</th>
        <th>Dish Type</th>
        <th>Price</th>
        <th>Description</th>
        {% if user.is_staff %}
          <th>Edit</th>
          <th>Create</th>
        {% endif %}
      </tr>
      {% for dish in dish_list %}
        <tr>
          {% if user.is_staff %}
            <td><a class="links" href="{% url "kitchen:dish-detail" pk=dish.id %}">{{ dish }}</a></td>
          {% else %}
            <td>{{ dish }}</td>
          {% endif %}
          <td>{{ dish.dish_type }}</td>
          <td>{{ dish.price }} {% if dish.price %} {% else %} - {% endif %}</td>
          <td>{{ dish.description }}</td>
          {% if user.is_staff %}
            <td><a class="links" href="{% url "kitchen:dish-update" pk=dish.id %}">Update </a><a class="links"
                                                                                                 href="{% url "kitchen:dish-delete" pk=dish.id %}">Delete</a>
            </td>
            <td><a class="links" href="{% url "kitchen:dish-create" %}">Create</a></td>
          {% endif %}
        </tr>
      {% endfor %}
    </table>
  </div>
{% endblock %}

templates/kitchen/dishtype_confirm_delete.html
{% extends "_base.html" %}

{% block content %}
    <h1>Are you sure you want to delete?</h1>
    <form action="" method="post">
      {% csrf_token %}

      <input type="submit" value="Yes" class="btn btn-danger">
    </form>
{% endblock %}

templates/kitchen/dishtype_detail.html
{% extends "_base.html" %}

{% block content %}
  <ul>
    <li>Name: {{ dishtype.name }}</li>
    <li><a href="{% url "kitchen:dish-type-delete" pk=dishtype.id %}">Delete {{ dishtype.name }}</a></li>
    <li><a href="{% url "kitchen:dish-type-update" pk=dishtype.id %}">Update {{ dishtype.name }}</a></li>
  </ul>
{% endblock %}

templates/kitchen/dishtype_form.html
{% extends "_base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish type</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/dishtype_list.html
{% extends "_base.html" %}

{% block content %}
  {% load static %}
  <link rel="stylesheet" href="{% static "css/settings.css" %}">
  <div class="element middle">
    <table class="table">
      <tr>
        <th>Dishes Types</th>
        {% if user.is_authenticated %}
          <th>Edit</th>
          <th>Create</th>
          </tr>
        {% endif %}
      {% for dish_type in dish_type_list %}
        <tr>
          {% if user.is_authenticated %}
            <td><a class="links" href="{% url "kitchen:dish-type-detail" pk=dish_type.id %}">{{ dish_type }}</a></td>
          {% else %}
            <td>{{ dish_type }}</td>
          {% endif %}
          {% if user.is_authenticated %}
            <td><a class="links" href="{% url "kitchen:dish-type-update" pk=dish_type.id %}">Update </a><a class="links"
                                                                                                           href="{% url "kitchen:dish-type-delete" pk=dish_type.id %}">Delete</a>
            </td>
            <td><a class="links" href="{% url "kitchen:dish-type-create" %}">Create</a></td>
          {% endif %}
        </tr>
      {% endfor %}
    </table>
  </div>
{% endblock %}

templates/kitchen/index.html
{% extends "_base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static "css/settings.css" %}">
    <div class="element middle index">
      <h1 class="title">Kitchen service</h1>
        <ul class="services-list">
        <li class="service-item">We have: {{ num_cooks }} cooks</li>
        <li class="service-item">More than {{ num_dish }} dishes</li>
        <li class="service-item">And {{ num_dish_type }} dishes types</li>
    </ul>
    </div>

{% endblock %}